### PR TITLE
Change output to format string.

### PR DESCRIPTION
**Pull request by lfernsy**
This simply replaces one of the print statements to use a format string, I don't have the time to get into details, but it's better to use format stings.

### CODE REVIEW

**Comment by lfernsy** [comment]
I'll fix that conflict soon.

**Comment by Tikolu** [comment]
Sorry, I don't fully understand. What exactly are "format strings"?

**Comment by lfernsy** [comment]
They are a method of string interpolation,
they allow you to put values in a preformatted string.

EXAMPLE:
    `"IP Address: {}".format(ip)`

_The **main** reason they are preferred is because you don't have to worry about type conversion._

**Comment by lfernsy** [comment]
**The Python documentation does a better job explaining it:
    [str.format()](https://docs.python.org/3/library/stdtypes.html#str.format)**

**Pull request merged**
