### PR TITLE
Improve structure.

### PR DESCRIPTION
**Pull request by lfernsy**
This PR restructures the project files to the [de facto standard](http://docs.python-guide.org/en/latest/writing/structure/) layout;

It also adds a **setup.py** file, allowing the user to _actually_ install the module.

### CODE REVIEW

**Comment by Tikolu** [comment]
Is this ready to merge?

**Comment by lfernsy** [comment]
Yes, I opened this as a PR so I could get your approval before pushing changes.

<sub>NOTE: My timezone is 6 hours behind your timezone, so don't except fast responses. (Based on location on profile)</sub>

**Comment by lfernsy** [comment]
I left out `Makefile` because that would be excessive for a small-scale project such as SETTI;
I left out `/tests` because... there's nothing to test.

Also, I can't make the `LICENSE` file for you, but I would recommend adding one soon.

**Comment by lfernsy** [comment]
Wait, there's a merge conflict; I'll close this PR until it's fixed.

**Comment by lfernsy** [comment]
Actually, since this repo as changed since when this was made, I'll just make a new PR.

**Pull request closed without merging**
